<?php // AUTO-GENERATED BY GRUNT. To change this block edit Gruntfile.js, not this file! ?>
<script type="text/javascript" src="/wp-content/themes/libtech/_/js/lib/jquery.fitvids.js"></script>
	<script type="text/javascript" src="/wp-content/themes/libtech/_/js/lib/jquery.bxslider.js"></script>
	<script type="text/javascript" src="/wp-content/themes/libtech/_/js/lib/jquery.magnific-popup.js"></script>
	<script type="text/javascript" src="/wp-content/themes/libtech/_/js/lib/jquery.treeview.js"></script>
	<script type="text/javascript" src="/wp-content/themes/libtech/_/js/lib/jquery.isotope.js"></script>
	<script type="text/javascript" src="/wp-content/themes/libtech/_/js/lib/froogaloop.js"></script>
	<script type="text/javascript" src="/wp-content/themes/libtech/_/js/libtech.main.js"></script>
